package command;

public enum CommandType {
    CREATE_SPPINT_MASTER,
    CREATE_DEVELOPER,
    CREATE_SPRINT,
    CREATE_TASK_FEATURE,
    CREATE_TASK_EPIC,
    CREATE_TASK_EPIC_STORY,
    CREATE_TASK_STORY,
    CREATE_TASK_BUG,
    PRINT_SPRINT_DETAILS,
    PRINT_SPRINT_DELAYED_TASKS,
    PRINT_TASK_DEVELOPERS
}
